name: Publish Github Pages

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Push Generated Results" ]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages-single
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout `auto_update` branch
        uses: actions/checkout@v6
        with:
          ref: auto_update
          fetch-depth: 0

      - name: Verify output directory and contents
        run: |
          if [ -d "out" ] && [ "$(ls -A out)" ]; then
              cd out
              echo "Contents in out:"
              ls -R
              mv output.md ../
          else
              echo "out directory is empty or does not exist. Aborting."
              exit 1
          fi

      - name: Check for latest.md
        id: check_files
        shell: bash
        run: |
          if [ -f latest.md ]; then
            echo "files_exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "files_exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Convert latest.md to pages
        uses: wranders/markdown-to-pages-action@v1.1.2
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: latest.md

      - name: Archive Pages artifact
        if: steps.check_files.outputs.files_exists == 'true'
        shell: bash
        run: |
          tar \
            --dereference --hard-dereference \
            --directory "dist" \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            --exclude=".[^/]*" \
            .

      - uses: actions/upload-artifact@v7
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          retention-days: 1
          if-no-files-found: error

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
        if: steps.check_files.outputs.files_exists == 'true'
        id: deployment
