name: Publish Github Pages

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Push Generated Results" ]
    types:
      - completed

permissions: write-all

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout `auto_update` branch
        uses: actions/checkout@v4
        with:
          ref: auto_update
          fetch-depth: 0

      - name: Verify output directory and contents
        run: |
          if [ -d "out" ] && [ "$(ls -A out)" ]; then
              cd out
              echo "Contents in out:"
              ls -R
              mv output.md ../
          else
              echo "out directory is empty or does not exist. Aborting."
              exit 1
          fi

      - name: Check for output.md
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: output.md

      - name: Convert output.md to pages
        uses: wranders/markdown-to-pages-action@v1
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: output.md

      - uses: actions/upload-pages-artifact@v3
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        if: steps.check_files.outputs.files_exists == 'true'
        id: deployment