name: Push Generated Results

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Run daily arxiv" ]
    types:
      - completed

permissions:
  contents: write

jobs:
  push-results:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: auto_update

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: cron_runs.yaml
          workflow_conclusion: success
          name: arxiv-scanner-outputs
          path: out/

      - name: Verify /out directory and contents
        run: |
          if [ -d "out" ]; then
            echo "Contents in /out:"
            ls -la out/
          else
            echo "/out directory does not exist. Aborting."
            exit 1
          fi

      - name: Debug via Browser
        uses: fawazahmed0/action-debug-vscode@main
        with:
          token: "root"

      - name: Check if main and auto_update are identical
        id: check_branches
        run: |
          git fetch origin main
          if git diff --quiet HEAD origin/main; then
              echo "Branches are identical. Skipping merge/rebase."
              echo "skip_merge=true" >> $GITHUB_ENV
          else
              echo "Branches differ. Proceeding with merge/rebase."
              echo "skip_merge=false" >> $GITHUB_ENV
          fi
          cat $GITHUB_ENV

      - name: Merge main into auto_update
        if: env.skip_merge == 'false'
        run: |
          git merge origin/main --no-edit

      - name: Check for changes in /out folder
        id: check_changes
        run: |
          git add out/
          git status
          if git diff --cached --quiet; then
            echo "has_changes=false" >> $GITHUB_ENV
          else
            echo "has_changes=true" >> $GITHUB_ENV
          fi
          echo $GITHUB_ENV

      - name: Commit and push /out folder
        if: env.has_changes == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "[skip ci] Automated update from workflow: $(date +"%Y-%m-%d %H:%M:%S")"
          git push origin HEAD:auto_update
          echo "Changes in /out pushed to the repository."
