name: Publish output MD to github pages (Multiple)

on:
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to `auto_update` Branch
        uses: actions/checkout@v3
        run: |
          git fetch origin
          if ! git show-ref --verify --quiet refs/remotes/origin/auto_update; then
            echo "auto_update branch does not exist. Creating it from main."
            git checkout -b auto_update origin/main
            git push origin auto_update
          else
            echo "auto_update branch exists. Checking out to it."
            git checkout -b auto_update origin/auto_update
          fi

      - name: Verify /out directory and contents
        run: |
          if [ -d "out" ] && [ "$(ls -A out)" ]; then
              echo "Contents in /out:"
              ls -la out/
          else
              echo "/out directory is empty or does not exist. Aborting."
              exit 1
          fi

      - name: Check for latest.md
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: latest.md

      - name: Convert latest.md to pages
        uses: wranders/markdown-to-pages-action@v1
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            out/latest.md
            out/index.md
            out/md/2025-01/index.md
            out/md/2025-02/index.md
            out/md/2025-03/index.md

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        if: steps.check_files.outputs.files_exists == 'true'
        id: deployment